spring:
  application:
    name: swipescript-backend
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
  h2:
    console:
      enabled: true

cloudinary:
  cloud-name: dalaqhrwy
  api-key: 266896446111645
  api-secret: lV279p1bgHGnS89EXmdgYCSpvZc
