server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  url: "${CLOUDINARY_URL}"

jwt:
  secret: "${JWT_SECRET}"

#app:
#  image:
#    url-prefix: "https://swipescript-test.us-east-1.elasticbeanstalk.com/images/"
